#!/bin/bash

# Establish the base repository reference directory
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $THIS_DIR/../../_local/development.env

export REPOSITORY_NAME=$REPOSITORY_NAME
export REPOSITORY_DIRECTORY=$REPOSITORY_DIRECTORY
export DEVELOPER_MODE=$DEVELOPER_MODE
export PYTHONPATH=$PYTHONPATH

echo "=================== Current Environment ==================="
echo "      REPOSITORY_NAME: ${REPOSITORY_NAME}"
echo " REPOSITORY_DIRECTORY: ${REPOSITORY_DIRECTORY}"
echo "       DEVELOPER_MODE: ${DEVELOPER_MODE}"
echo "           PYTHONPATH: ${PYTHONPATH}"

python "$THIS_DIR/show-env.py"
